isaaclab_task: "Nami-Nav-Deploy"

communication:
  topic_namespace: "nami_sim"
  zenoh: null

simulation:
  real_time: true
  max_steps: null

commands:
  - topic: "action_command"
    dtype: "float32"
    action_slice: [0, 2]

observations:
  root: "obs"

keyboard:
  command_topic: "action_command"
  linear_speed: 1.0
  yaw_speed: 1.0
  debug_vis: false
