isaaclab_task: "Moby-Deploy"


communication:
  topic_namespace: "isaaclab/moby_sim"
  shm_config: # TODO: add shared memory config options if needed
    enabled: false
    shm_size: 256 * 1024 * 1024  # 256 MB

  # TODO: add Zenoh config options if needed
